runtime: python37
service: user

default_expiration: "4d"

handlers:
        - url: /static
          static_dir: static

        - url: /(.*\.(css))$
          expiration: "20m"
          static_files: static/css/\1
          upload: static/css/.*\.(css)$

        - url: /(.*\.(js))$
          expiration: "1m"
          static_files: static/js/\1
          upload: static/js/.*\.(js)$
        
        - url: /.*
          expiration: "1m"
          static_files: index.html
          upload: index.html
          secure: always
