runtime: python37
service: admin

handlers:
        - url: /static
          static_dir: static

        - url: /(.*\.(css))$
          static_files: static/css/\1
          upload: static/css/.*\.(css)$

        - url: /(.*\.(js))$
          static_files: static/js/\1
          upload: static/js/.*\.(js)$
        
        - url: /.*
          static_files: index.html
          upload: index.html
